# Generated by Django 5.1.4 on 2025-06-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile'),
        ),
    ]
