# Generated by Django 5.1.4 on 2024-12-26 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profilemodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
