# Generated by Django 5.1.4 on 2025-06-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profilemodel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
