# Generated by Django 5.1.4 on 2025-06-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profilemodel_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
