# Generated by Django 5.1.4 on 2024-12-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profilemodel_address_profilemodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='date_od_birth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
