# Generated by Django 5.1.4 on 2024-12-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_date_od_birth_profilemodel_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='date_of_birth',
        ),
    ]
