# Generated by Django 5.1.4 on 2025-04-13 15:00

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('hotel', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveIntegerField(choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='HotelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=13, null=True, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif'])])),
                ('dated_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('-dated_on',),
                'indexes': [models.Index(fields=['-dated_on'], name='core_hotelp_dated_o_eab506_idx')],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('hotel_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hotelpost')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OurRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True, null=True)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list of amenities', null=True)),
                ('check_in_time', models.TimeField(default=datetime.time(15, 0))),
                ('check_out_time', models.TimeField(default=datetime.time(11, 0))),
                ('max_guests', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bed_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King')], default='double', max_length=100)),
                ('bed_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('room_size', models.CharField(blank=True, help_text='e.g., 25 m²', max_length=50, null=True)),
                ('room_view', models.CharField(blank=True, help_text='e.g., Ocean View', max_length=100, null=True)),
                ('image', models.ImageField(upload_to='rooms/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.hotelpost')),
                ('star_rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rating')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OurRoomsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif'])])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ourroom')),
            ],
            options={
                'verbose_name_plural': 'Our Rooms Images',
                'ordering': ('room',),
            },
        ),
        migrations.AddIndex(
            model_name='ourroom',
            index=models.Index(fields=['available', 'price'], name='core_ourroo_availab_7d6df5_idx'),
        ),
        migrations.AddIndex(
            model_name='ourroom',
            index=models.Index(fields=['bed_type', 'max_guests'], name='core_ourroo_bed_typ_584cfa_idx'),
        ),
    ]
