# Generated by Django 5.1.4 on 2025-09-06 14:16

import cloudinary.models
import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('hotel_name', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveIntegerField(choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Hotel Manager'), ('Guest', 'Guest'), ('staff', 'Staff')], default='Guest', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('username',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(choices=[('GA', 'Greater Accra'), ('NR', 'Northern'), ('AS', 'Ashanti'), ('CR', 'Central'), ('WR', 'Western'), ('VR', 'Volta'), ('ER', 'Eastern'), ('UW', 'Upper West'), ('UE', 'Upper East'), ('SR', 'Savannah'), ('NE', 'North East'), ('BE', 'Bono East'), ('OR', 'Oti'), ('AR', 'Ahafo'), ('BR', 'Bono'), ('WN', 'Western North')], max_length=2, null=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('hotel_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Hotel Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='hotels', to='core.amenity')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('hotel_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hotel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('check_in_date', models.DateField(verbose_name='Check-in Date')),
                ('check_out_date', models.DateField(verbose_name='Check-out Date')),
                ('check_in_time', models.TimeField(default=datetime.time(15, 0), verbose_name='Check-in Time')),
                ('check_out_time', models.TimeField(default=datetime.time(11, 0), verbose_name='Check-out Time')),
                ('num_adults', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Adults')),
                ('num_children', models.PositiveSmallIntegerField(default=0, verbose_name='Number of Children')),
                ('num_guests', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Number of Guests')),
                ('status', models.CharField(choices=[('Pending', 'Pending Confirmation'), ('Confirmed', 'Confirmed'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Pending', max_length=20, verbose_name='Status')),
                ('price_per_night_at_booking', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price Per Night At Booking')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Price')),
                ('booking_source', models.CharField(blank=True, help_text='e.g., Online, Phone, Walk-in, OTA Name', max_length=50, null=True, verbose_name='Booking Source')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes/Requests')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Booked On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.guest', verbose_name='Guest')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ('check_in_date', 'check_in_time', 'room__room_number'),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rating')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.reservation')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('family', 'Family')], default='single', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Maintenance', 'Maintenance'), ('Occupied', 'Occupied'), ('Unavailable', 'Temporarily Unavailable')], default='Available', max_length=20, verbose_name='Physical Status')),
                ('max_guests', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bed_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King')], default='double', max_length=100)),
                ('room_number', models.CharField(max_length=10, null=True, verbose_name='Room Number')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='rooms', to='core.amenity', verbose_name='Amenities')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.hotel')),
                ('star_rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rating')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.room', verbose_name='Room'),
        ),
        migrations.CreateModel(
            name='OurRoomsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
            options={
                'verbose_name_plural': 'Our Rooms Images',
                'ordering': ('room',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.guest')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.room')),
            ],
            options={
                'verbose_name': 'Online Booking',
                'verbose_name_plural': 'Online Bookings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service, e.g., Room Service', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the service', null=True)),
                ('category', models.CharField(choices=[('RS', 'Room Service'), ('FB', 'Food & Beverage'), ('WL', 'Wellness'), ('TR', 'Transportation'), ('BZ', 'Business'), ('LN', 'Laundry & Dry Cleaning'), ('AC', 'Activities/Tours'), ('CC', 'Concierge'), ('FR', 'Facility Rental (Meeting Rooms, etc.)'), ('OT', 'Other')], default='OT', help_text='Category of the service', max_length=2)),
                ('is_available', models.BooleanField(default=True, help_text='Is this service currently offered?')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ManyToManyField(help_text='Hotels that offer this service', related_name='services_hotels', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='hotels_services', to='core.service'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(choices=[('manager', 'Manager'), ('receptionist', 'Receptionist'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('chef', 'Chef'), ('waiter', 'Waiter'), ('security', 'Security'), ('other', 'Other')], max_length=50)),
                ('department', models.CharField(choices=[('management', 'Management'), ('front_desk', 'Front Desk'), ('housekeeping', 'Housekeeping'), ('food_beverage', 'Food & Beverage'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('other', 'Other')], max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='core.hotel')),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['-join_date'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['-created_at'], name='core_custom_created_d15d02_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['last_name', 'first_name'], name='core_guest_last_na_b44cba_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['email'], name='core_guest_email_3f4bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['phone_number'], name='core_guest_phone_n_351e05_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reservation'], name='core_review_reserva_5b9262_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='core_review_rating__40f0d2_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', 'price'], name='core_room_status_a91d51_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_number', 'max_guests'], name='core_room_room_nu_6d4b01_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['check_in_date', 'check_out_date'], name='core_reserv_check_i_ff0959_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'check_in_date', 'check_out_date'], name='core_reserv_room_id_765de8_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['guest'], name='core_reserv_guest_i_35eae4_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='core_reserv_status_3b8861_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest', 'created_at'], name='core_bookin_guest_i_2d0976_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['is_paid', 'created_at'], name='core_bookin_is_paid_1acbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['paystack_reference'], name='core_bookin_paystac_0daff3_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['name'], name='core_hotel_name_7bc4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['region'], name='core_hotel_region_bd21ae_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['-created_at'], name='core_hotel_created_18ca50_idx'),
        ),
    ]
