# Generated by Django 5.1.4 on 2025-04-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpost',
            name='region',
            field=models.CharField(choices=[('GA', 'Greater Accra'), ('NR', 'Northern'), ('AS', 'Ashanti'), ('CR', 'Central'), ('WR', 'Western'), ('VR', 'Volta'), ('ER', 'Eastern'), ('UW', 'Upper West'), ('UE', 'Upper East'), ('SR', 'Savannah'), ('NE', 'North East'), ('BE', 'Bono East'), ('OR', 'Oti'), ('AR', 'Ahafo'), ('BR', 'Bono'), ('WN', 'Western North')], max_length=2, null=True),
        ),
    ]
