# Generated by Django 5.1.4 on 2025-10-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
