# Generated by Django 5.1.4 on 2025-05-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='mesaage',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
    ]
