# Generated by Django 5.1.4 on 2025-10-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_hotel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Hotel Manager'), ('Guest', 'Guest')], default='Guest', max_length=20),
        ),
    ]
