# Generated by Django 5.1.4 on 2025-04-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hotelpost_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourroom',
            name='room_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
