# Generated by Django 5.1.4 on 2024-12-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hotelpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelpost',
            old_name='hotel_name',
            new_name='name',
        ),
    ]
