# Generated by Django 5.1.4 on 2025-05-02 16:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservation_email_reservation_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service, e.g., Room Service', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the service', null=True)),
                ('category', models.CharField(choices=[('RS', 'Room Service'), ('FB', 'Food & Beverage'), ('WL', 'Wellness'), ('TR', 'Transportation'), ('BZ', 'Business'), ('LN', 'Laundry & Dry Cleaning'), ('AC', 'Activities/Tours'), ('CC', 'Concierge'), ('FR', 'Facility Rental (Meeting Rooms, etc.)'), ('OT', 'Other')], default='OT', help_text='Category of the service', max_length=2)),
                ('is_available', models.BooleanField(default=True, help_text='Is this service currently offered?')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_hotel', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='core.service'),
        ),
    ]
