# Generated by Django 5.1.4 on 2025-05-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service_hotel_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='hotels_services', to='core.service'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='hotel',
        ),
        migrations.AddField(
            model_name='service',
            name='hotel',
            field=models.ManyToManyField(help_text='Hotels that offer this service', related_name='services_hotels', to='core.hotel'),
        ),
    ]
