# Generated by Django 5.1.4 on 2024-12-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_leads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leads',
            new_name='Lead',
        ),
    ]
