# Generated by Django 5.1.4 on 2025-04-19 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_delete_userlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.hotelpost'),
        ),
    ]
