# Generated by Django 5.1.4 on 2025-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_replace_paystack_with_flutterwave'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='core_bookin_paystac_0daff3_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='hubtel_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hubtel_reference'], name='core_bookin_hubtel__b0adeb_idx'),
        ),
    ]
