# Generated by Django 5.1.4 on 2025-12-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_booking_core_bookin_paystac_0daff3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='paystack_reference',
        ),
    ]
