# Generated by Django 5.1.4 on 2025-05-03 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_image/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif', 'webp'])]),
        ),
    ]
