# Generated by Django 5.1.4 on 2025-12-11 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_booking_paystack_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPaystackSubaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subaccount_code', models.CharField(help_text='Unique code from Paystack dashboard (e.g., ACCT_xyz123)', max_length=100, unique=True, verbose_name='Paystack Subaccount Code')),
                ('business_name', models.CharField(help_text='Business name as registered in Paystack', max_length=200, verbose_name='Business Name on Paystack')),
                ('settlement_bank', models.CharField(help_text='Bank name for receiving payments', max_length=100, verbose_name='Settlement Bank')),
                ('account_number', models.CharField(help_text="Hotel's bank account number", max_length=20, verbose_name='Account Number')),
                ('percentage_charge', models.DecimalField(decimal_places=2, default=15.0, help_text='Percentage that goes to platform (e.g., 15.00 for 15%)', max_digits=5, verbose_name='Platform Commission %')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable split payments for this hotel', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_settlement_date', models.DateField(blank=True, null=True, verbose_name='Last Settlement Date')),
                ('total_payments_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Payments Received')),
            ],
            options={
                'verbose_name': 'Hotel Paystack Subaccount',
                'verbose_name_plural': 'Hotel Paystack Subaccounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='core_bookin_hubtel__b0adeb_idx',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='hubtel_reference',
            new_name='paystack_reference',
        ),
        migrations.AddField(
            model_name='booking',
            name='paystack_access_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_payment_setup',
            field=models.BooleanField(default=False, verbose_name='Payment Setup Complete'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['paystack_reference'], name='core_bookin_paystac_0daff3_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['has_payment_setup'], name='core_hotel_has_pay_aa1e79_idx'),
        ),
        migrations.AddField(
            model_name='hotelpaystacksubaccount',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_subaccount', to='core.hotel', verbose_name='Hotel'),
        ),
        migrations.AddIndex(
            model_name='hotelpaystacksubaccount',
            index=models.Index(fields=['subaccount_code'], name='core_hotelp_subacco_269b70_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelpaystacksubaccount',
            index=models.Index(fields=['is_active'], name='core_hotelp_is_acti_73998e_idx'),
        ),
    ]
