# Generated by Django 5.1.4 on 2025-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_booking_hotel_name_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hotel_name',
            new_name='hotel',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
