# Generated by Django 5.1.4 on 2025-05-03 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_hotel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_photo/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif', 'webp'])], verbose_name='Hotel Image'),
        ),
    ]
