# Generated by Django 5.1.4 on 2025-04-20 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_hotel_name_booking_hotel_booking_check_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='ourroom',
            name='core_ourroo_availab_7d6df5_idx',
        ),
        migrations.RemoveIndex(
            model_name='ourroom',
            name='core_ourroo_bed_typ_584cfa_idx',
        ),
        migrations.RemoveField(
            model_name='ourroom',
            name='available',
        ),
        migrations.RemoveField(
            model_name='ourroom',
            name='bed_count',
        ),
        migrations.RemoveField(
            model_name='ourroom',
            name='bed_type',
        ),
        migrations.RemoveField(
            model_name='ourroom',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ourroom',
            name='room_size',
        ),
        migrations.RemoveField(
            model_name='ourroom',
            name='room_view',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
        migrations.AddField(
            model_name='ourroom',
            name='check_in_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ourroom',
            name='check_out_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ourroom',
            name='room_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ourroom',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('M', 'Maintenance'), ('O', 'Occupied')], default='A', max_length=1, null=True),
        ),
        migrations.RemoveField(
            model_name='ourroom',
            name='amenities',
        ),
        migrations.AlterField(
            model_name='ourroom',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King')], default='double', max_length=100),
        ),
        migrations.AddIndex(
            model_name='ourroom',
            index=models.Index(fields=['status', 'price'], name='core_ourroo_status_423123_idx'),
        ),
        migrations.AddIndex(
            model_name='ourroom',
            index=models.Index(fields=['room_number', 'max_guests'], name='core_ourroo_room_nu_3a8ab6_idx'),
        ),
        migrations.AddField(
            model_name='ourroom',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, to='core.amenity'),
        ),
    ]
