# Generated by Django 5.1.4 on 2025-04-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourroom',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='core.amenity'),
        ),
    ]
