# Generated by Django 5.1.4 on 2025-05-03 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_hotel_image_hotel_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif', 'webp'])], verbose_name='Hotel Image'),
        ),
    ]
