# Generated by Django 5.1.4 on 2025-04-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ourroom_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourroom',
            name='room_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
