# Generated by Django 5.1.4 on 2025-05-04 17:35

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_hotel_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif', 'webp'])], verbose_name='Hotel Image'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='ourroomsimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'jfif'])]),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
