# Generated by Django 5.1.4 on 2025-04-22 08:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_ourroom_room_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='staff_profile_pics/')),
                ('position', models.CharField(choices=[('manager', 'Manager'), ('receptionist', 'Receptionist'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('chef', 'Chef'), ('waiter', 'Waiter'), ('security', 'Security'), ('other', 'Other')], max_length=50)),
                ('department', models.CharField(choices=[('management', 'Management'), ('front_desk', 'Front Desk'), ('housekeeping', 'Housekeeping'), ('food_beverage', 'Food & Beverage'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('other', 'Other')], max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='core.hotelpost')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['-join_date'],
            },
        ),
    ]
