# Generated by Django 5.1.4 on 2025-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_staff_user_staff_email_staff_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
