# Generated by Django 5.1.4 on 2025-04-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_lead_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='hotel_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
