# Generated by Django 5.1.4 on 2025-06-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_booking_is_seen_booking_seen_at_reservation_is_seen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone_number',
        ),
    ]
