# Generated by Django 5.1.4 on 2025-06-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_booking_email_remove_booking_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seen_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seen_at',
        ),
    ]
