# Generated by Django 5.1.4 on 2025-04-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_booking_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='name',
            new_name='amenity_name',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='description',
        ),
    ]
