# Generated by Django 5.1.4 on 2025-06-26 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_booking_is_seen_remove_booking_seen_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='star_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rating'),
        ),
    ]
