# Generated by Django 5.1.4 on 2025-04-26 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_name_amenity_amenity_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourroom',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='ourroom',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='ourroom',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='ourroom',
            name='check_out_time',
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hotelpost')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_bookings', to='core.ourroom')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[('C', 'Confirmed'), ('I', 'Checked-in'), ('O', 'Checked-out'), ('X', 'Cancelled')], default='C', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ourroom')),
            ],
        ),
    ]
