# Generated by Django 5.1.4 on 2025-06-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_room_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='amenity_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
