# Generated by Django 5.1.4 on 2025-08-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_booking_is_paid_booking_paystack_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-created_at',), 'verbose_name': 'Online Booking', 'verbose_name_plural': 'Online Bookings'},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest', 'created_at'], name='core_bookin_guest_i_2d0976_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['is_paid', 'created_at'], name='core_bookin_is_paid_1acbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['paystack_reference'], name='core_bookin_paystac_0daff3_idx'),
        ),
    ]
