"""
Django settings for hotelapp project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
import cloudinary,cloudinary_storage # type: ignore
import dj_database_url # type: ignore

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", False))

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(' ')
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in debug mode
if not DEBUG:
    CORS_ALLOWED_ORIGINS = [
        'https://baselink.onrender.com',
    ]


CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost').split(' ')
CSRF_TRUSTED_ORIGINS = [
    'https://baselink.onrender.com', 
]


# Application definition

INSTALLED_APPS = [
    'core',
    'account',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    
    'crispy_forms',
    "crispy_tailwind",
    'tailwind',
    'theme',
    'django_browser_reload',
    'pwa',
]
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"
TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

ROOT_URLCONF = 'hotelapp.urls'

# Set session to expire after 15 minutes of **inactivity**
SESSION_COOKIE_AGE = 900  # 900 seconds = 15 minutes

# Log user out when browser is closed (optional but recommended)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Refresh session expiration on each request (to detect activity)
SESSION_SAVE_EVERY_REQUEST = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'account.context_processors.hotel_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotelapp.wsgi.application'
NPM_BIN_PATH = 'npm.cmd'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': os.environ.get("DB_ENGINE", "django.db.backends.postgresql"),
#         'NAME': os.environ.get("DB_NAME", ""),
#         'USER': os.environ.get("DB_USER", ""),
#         'PASSWORD': os.environ.get("DB_PASSWORD", ""),
#         'HOST': os.environ.get("DB_HOST", ""),
#         'PORT': os.environ.get("DB_PORT", ""),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core', 'static')
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media/'


LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'home'

AUTH_USER_MODEL = 'core.CustomUser'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET')
}

# PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')  # Replace with your actual secret key
# PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')  # For frontend

# HUBTEL Payment Gateway Configuration (Ghana-optimized with native split payment support)
HUBTEL_API_KEY = os.getenv('HUBTEL_API_KEY')  # Your HUBTEL API key (Bearer token)
HUBTEL_SECRET_KEY = os.getenv('HUBTEL_SECRET_KEY')  # Your HUBTEL secret key for webhook verification
HUBTEL_CURRENCY = os.getenv('HUBTEL_CURRENCY', 'GHS')  # Currency code (GHS for Ghana)

DEFAULT_HOTEL_EMAIL = 'esmondabban@gmail.com'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL =  os.getenv('DEFAULT_FROM_EMAIL')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'hotelapp.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'core': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'account': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# PWA Configuration
PWA_APP_NAME = 'BaseLink'
PWA_APP_DESCRIPTION = "A Hotel Management Application"
PWA_APP_THEME_COLOR = '#3B82F6'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    # Use BaseLink logo for all sizes to ensure consistent branding
    {
        'src': '/static/image/assets/BASELINK-LOGO.png',
        'sizes': '72x72',
        'type': 'image/png'
    },
    {
        'src': '/static/image/assets/BASELINK-LOGO.png',
        'sizes': '96x96',
        'type': 'image/png'
    },
    {
        'src': '/static/image/assets/BASELINK-LOGO.png',
        'sizes': '128x128',
        'type': 'image/png'
    },
    {
        'src': '/static/image/assets/BASELINK-LOGO.png',
        'sizes': '144x144',
        'type': 'image/png'
    },
    {
        'src': '/static/image/assets/BASELINK-LOGO.png',
        'sizes': '152x152',
        'type': 'image/png'
    },
    {
        'src': '/static/image/assets/BASELINK-LOGO.png',
        'sizes': '192x192',
        'type': 'image/png',
        'purpose': 'any maskable'
    },
    {
        'src': '/static/image/assets/BASELINK-LOGO.png',
        'sizes': '384x384',
        'type': 'image/png',
        'purpose': 'any maskable'
    },
    {
        'src': '/static/image/assets/BASELINK-LOGO.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any maskable'
    },
    # Add a specific icon for PWA install dialog
    {
        'src': '/static/image/assets/BASELINK-LOGO.png',
        'sizes': '192x192',
        'type': 'image/png',
        'purpose': 'any'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/image/assets/BASELINK-LOGO.png',
        'sizes': '180x180',
        'type': 'image/png'
    },
    {
        'src': '/static/image/assets/BASELINK-LOGO.png',
        'sizes': '192x192',
        'type': 'image/png'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/icons/splash-640x1136.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
PWA_APP_SHORTCUTS = [
    {
        'name': 'Book a Room',
        'url': '/hotel_rooms/',
        'description': 'Browse and book hotel rooms',
        'icons': [
            {
                'src': '/static/image/assets/BASELINK-LOGO.png',
                'sizes': '192x192',
                'type': 'image/png'
            }
        ]
    },
    {
        'name': 'My Bookings',
        'url': '/my_booking/',
        'description': 'View your hotel bookings',
        'icons': [
            {
                'src': '/static/image/assets/BASELINK-LOGO.png',
                'sizes': '192x192',
                'type': 'image/png'
            }
        ]
    },
    {
        'name': 'Contact Us',
        'url': '/contact/',
        'description': 'Get in touch with us',
        'icons': [
            {
                'src': '/static/image/assets/BASELINK-LOGO.png',
                'sizes': '192x192',
                'type': 'image/png'
            }
        ]
    }
]
PWA_APP_SCREENSHOTS = [
    {
      'src': '/static/images/icons/splash-750x1334.png',
      'sizes': '750x1334',
      "type": "image/png"
    }
]
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'core', 'static/js/serviceworker.js')